baseURL = "https://bono0621.github.io/"
languageCode = "en-us"
title = "Hwan's Place"

[params]
  description = "Personal portfolio and CV"
  author = "Hwan's Place"

[markup.goldmark.renderer]
  unsafe = true
